version: '3'

services:
  vs-code-debugging:
    image: vs-code-debugging
    build: .
    volumes:
      - ./:/app/
      - /app/node_modules
    ports:
      - '3000:3000'
      - '9229:9229'
    links:
      - mongodb
    depends_on:
      - mongodb
    command: ['npm', 'run', 'start-dev']
  mongodb:
    image: mongo:4.1
